use_frameworks!

platform :ios, '9.0'

target 'GBNetworking_Example' do
  pod 'GBNetworking', :path => '../'

  target 'GBNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
